# Generated by Django 2.0.5 on 2018-05-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('binomial_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_source', models.CharField(blank=True, max_length=255)),
                ('food', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('sound', models.TextField(blank=True)),
                ('talking', models.TextField(blank=True)),
                ('social', models.TextField(blank=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
