# Generated by Django 2.0.5 on 2018-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0002_breed_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='pet_information',
            field=models.TextField(blank=True),
        ),
    ]
