# Generated by Django 2.0.5 on 2018-05-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0003_breed_pet_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='breeding',
            field=models.TextField(blank=True),
        ),
    ]
