# Generated by Django 2.0.5 on 2018-05-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0005_auto_20180525_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breeding',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='breed',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='breed',
            name='description_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='breed',
            name='food',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='breed',
            name='pet_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='social',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='breed',
            name='sound',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='breed',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='breed',
            name='talking',
            field=models.TextField(blank=True, default=''),
        ),
    ]
