# Generated by Django 2.0.5 on 2018-05-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0006_auto_20180525_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='binomial_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
