# Generated by Django 2.0.5 on 2018-05-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0007_auto_20180525_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='binomial_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
