# Generated by Django 2.0.5 on 2018-05-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0009_auto_20180525_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='binomial_name',
            field=models.CharField(blank=True, default='a', max_length=255),
        ),
    ]
