# Generated by Django 2.0.5 on 2018-05-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0010_auto_20180525_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breeding',
            field=models.TextField(blank=True, default='aaaa'),
        ),
    ]
