# Generated by Django 2.0.5 on 2018-05-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0011_auto_20180525_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='binomial_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='breeding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='description_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='food',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='pet_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='social',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='sound',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='talking',
            field=models.TextField(blank=True, null=True),
        ),
    ]
