# Generated by Django 2.0.5 on 2018-05-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0012_auto_20180525_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
