# Generated by Django 2.0.5 on 2018-05-26 00:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0014_auto_20180526_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breeding',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='food',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='pet_information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='social',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='sound',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='talking',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
