# Generated by Django 2.0.5 on 2018-05-26 01:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0015_auto_20180526_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
