# Generated by Django 2.0.5 on 2018-05-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0018_breedimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreedImages',
            new_name='BreedImage',
        ),
    ]
