# Generated by Django 2.0.5 on 2018-06-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0022_auto_20180604_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedimage',
            name='featured',
            field=models.NullBooleanField(),
        ),
    ]
