# Generated by Django 2.0.5 on 2018-06-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0023_breedimage_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedimage',
            name='featured',
            field=models.NullBooleanField(default=0),
        ),
    ]
