# Generated by Django 2.0.5 on 2018-06-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0024_auto_20180607_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedimage',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
