# Generated by Django 2.0.5 on 2018-06-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0025_auto_20180615_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedimage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
