# Generated by Django 2.0.5 on 2018-06-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0029_auto_20180615_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedimage',
            name='title',
            field=models.CharField(default='Image', max_length=255),
        ),
    ]
