# Generated by Django 2.0.5 on 2018-06-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0032_auto_20180616_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedimage',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
