# Generated by Django 2.0.5 on 2018-06-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0033_auto_20180616_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedimage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
